# Logging Related
LOG_STATUS_ERROR_1 		= "ERROR"
LOG_STATUS_SUCCESS_1 	= "SUCCESS"
LOG_OMS_RESPONSE_1 		= "RS-Log"
LOG_INTERNAL_REPONSE_1  = "FY-Log"

LOG_STATUS_REQUEST_1    =   "REQUEST"

#Cache Key expiries in seconds
CACHE_T_1 	= 3600
CACHE_T_2 	= 21600
CACHE_T_3 	= 43200
CACHE_T_4	= 86400

# Seconds
SECONDS_1DAY = 86400

# Encoding Types
ENCODING_TYPE_UTF8      = "utf8"

# Preventing SQL Injections
MYSQL_INJECTION_PREVENT_1 = "insert"
MYSQL_INJECTION_PREVENT_2 = "update"
MYSQL_INJECTION_PREVENT_3 = "select"
MYSQL_INJECTION_PREVENT_4 = "drop"
MYSQL_INJECTION_PREVENT_5 = "count"

MYSQL_INJECTION_PREVENT_LIST = [MYSQL_INJECTION_PREVENT_1,MYSQL_INJECTION_PREVENT_2,MYSQL_INJECTION_PREVENT_3,MYSQL_INJECTION_PREVENT_4,MYSQL_INJECTION_PREVENT_5]

# Html Status Message Alert Type
HTML_MSG_TYPE_NEUTRAL    = "1"
HTML_MSG_TYPE_SUCCESS    = "2"
HTML_MSG_TYPE_WARNING    = "-1"
HTML_MSG_TYPE_FAIL       = "-2"

# Regular expression format to check for desired format
STRING_FORMAT_FYERSID       = "^[A-Z]{2}[0-9]{3,5}$"