DEMO_ORDERBOOK = [{
					"status": 2,
					"exchange": "BSE",
					"symbol": "BSE:SBIN-A",
					"limitPrice": 0,
					"qty": 1,
					"orderNumStatus": "806236260251:2",
					"dqQtyRem": 0,
					"orderValidity": "DAY",
					"slNo": 1,
					"message": "TRADE CONFIRMED",
					"segment": "M",
					"id": "806236260251",
					"stopPrice": 0,
					"filledQty": 0,
					"exchOrdId": "262017500018880",
					"remainingQuantity": 1,
					"offlineOrder": False,
					"instrument": "EQUITY",
					"tradedPrice": 0,
					"productType": "INTRADAY",
					"type": 2,
					"side": 1,
					"discloseQty": 0,
					"orderDateTime": "",
					"clientId": "***01",
					"pan": "****00A",
					"fyToken": "1210000000500112",
					"ex_sym": "SBIN",
					"ch": -19,
					"chp": -0.04,
					"lp": 48566,
					"description": "STATE BANK OF INDIA",
				},
				{
					"status": 2,
					"exchange": "BSE",
					"symbol": "BSE:SBIN-A",
					"limitPrice": 0,
					"qty": 1,
					"orderNumStatus": "806236260274:2",
					"dqQtyRem": 0,
					"orderValidity": "DAY",
					"slNo": 2,
					"message": "TRADE CONFIRMED",
					"segment": "M",
					"id": "806236260274",
					"stopPrice": 0,
					"filledQty": 0,
					"exchOrdId": "262017156828880",
					"remainingQuantity": 1,
					"offlineOrder": False,
					"instrument": "EQUITY",
					"tradedPrice": 0,
					"productType": "INTRADAY",
					"type": 2,
					"side": -1,
					"discloseQty": 0,
					"orderDateTime": "",
					"clientId": "***01",
					"pan": "****00A",
					"fyToken": "1210000000500112",
					"ex_sym": "SBIN",
					"ch": -19,
					"chp": -0.04,
					"lp": 48566,
					"description": "STATE BANK OF INDIA",
				},
				{
					"status": 2,
					"exchange": "BSE",
					"symbol": "BSE:RELIANCE-A",
					"limitPrice": 0,
					"qty": 1,
					"orderNumStatus": "806236260251:2",
					"dqQtyRem": 0,
					"orderValidity": "DAY",
					"slNo": 3,
					"message": "TRADE CONFIRMED",
					"segment": "M",
					"id": "806236260251",
					"stopPrice": 0,
					"filledQty": 0,
					"exchOrdId": "262017500018880",
					"remainingQuantity": 1,
					"offlineOrder": False,
					"instrument": "EQUITY",
					"tradedPrice": 0,
					"productType": "CNC",
					"type": 1,
					"side": 1,
					"discloseQty": 0,
					"orderDateTime": "",
					"clientId": "***01",
					"pan": "****00A",
					"fyToken": "1210000000500112",
					"ex_sym": "RELIANCE",
					"ch": -19,
					"chp": -0.04,
					"lp": 48566,
					"description": "",
				},
				{
					"status": 2,
					"exchange": "BSE",
					"symbol": "BSE:RELIANCE-A",
					"limitPrice": 0,
					"qty": 1,
					"orderNumStatus": "806236260251:2",
					"dqQtyRem": 0,
					"orderValidity": "DAY",
					"slNo": 4,
					"message": "TRADE CONFIRMED",
					"segment": "M",
					"id": "806236260251",
					"stopPrice": 0,
					"filledQty": 0,
					"exchOrdId": "262017500018880",
					"remainingQuantity": 1,
					"offlineOrder": False,
					"instrument": "EQUITY",
					"tradedPrice": 0,
					"productType": "CNC",
					"type": 2,
					"side": -1,
					"discloseQty": 0,
					"orderDateTime": "",
					"clientId": "***01",
					"pan": "****00A",
					"fyToken": "1210000000500112",
					"ex_sym": "RELIANCE",
					"ch": -19,
					"chp": -0.04,
					"lp": 48566,
					"description": "",
				},
				{
		            "status": 5,
		            "ex_sym": "RELIANCE",
		            "ch": -36.85,
		            "lp": 2096.35,
		            "exchange": "BSE",
		            "symbol": "BSE:RELIANCE-A",
		            "limitPrice": 2096.35,
		            "qty": 1,
		            "orderNumStatus": "1200820175431-CO-1:5",
		            "dqQtyRem": 0,
		            "orderDateTime": "",
		            "orderValidity": "DAY",
		            "fyToken": "1210000000500325",
		            "slNo": 5,
		            "message": "RMS:1200820175431:TRIGGER PRICE IS OUT OF THE SPECIFIED PRICE RANGE",
		            "segment": "E",
		            "id": "1200820175431-CO-1",
		            "stopPrice": 0.0,
		            "description": "RELIANCE INDUSTRIES LTD.",
		            "exchOrdId": "0",
		            "remainingQuantity": 1,
		            "filledQty": 0,
		            "clientId": "***01",
		            "offlineOrder": False,
		            "chp": -1.73,
		            "instrument": "EQUITY",
		            "tradedPrice": 0.0,
		            "productType": "CO",
		            "type": 1,
		            "side": 1,
		            "pan": "****00A",
		            "discloseQty": 0,
		        },
		        {
		            "status": 5,
		            "ex_sym": "HDFCBANK",
		            "ch": -8.8,
		            "lp": 1058.6,
		            "exchange": "BSE",
		            "symbol": "BSE:HDFCBANK-A",
		            "limitPrice": 0.0,
		            "qty": 1,
		            "orderNumStatus": "1200820175441-BO-1:5",
		            "dqQtyRem": 0,
		            "orderDateTime": "",
		            "orderValidity": "DAY",
		            "fyToken": "1210000000500180",
		            "slNo": 6,
		            "message": "RMS:1200820175441:Not allowed to trade in BSE EQ",
		            "segment": "E",
		            "id": "1200820175441-BO-1",
		            "stopPrice": 0.0,
		            "description": "HDFC BANK LTD.",
		            "exchOrdId": "0",
		            "remainingQuantity": 1,
		            "filledQty": 0,
		            "clientId": "***01",
		            "offlineOrder": False,
		            "chp": -0.82,
		            "instrument": "EQUITY",
		            "tradedPrice": 0.0,
		            "productType": "BO",
		            "type": 2,
		            "side": -1,
		            "pan": "****00A",
		            "discloseQty": 0,
		        },
		        {
		            "status": 5,
		            "ex_sym": "ACC",
		            "ch": -8.5,
		            "lp": 1421.0,
		            "exchange": "BSE",
		            "symbol": "BSE:ACC-A",
		            "limitPrice": 0.0,
		            "qty": 1,
		            "orderNumStatus": "1200820175451:5",
		            "dqQtyRem": 0,
		            "orderDateTime": "",
		            "orderValidity": "DAY",
		            "fyToken": "1210000000500410",
		            "slNo": 7,
		            "message": "RMS:1200820175451:Not allowed to trade in BSE EQ",
		            "segment": "E",
		            "id": "1200820175451",
		            "stopPrice": 0.0,
		            "description": "ACC LTD.",
		            "exchOrdId": "0",
		            "remainingQuantity": 1,
		            "filledQty": 0,
		            "clientId": "***01",
		            "offlineOrder": False,
		            "chp": -0.59,
		            "instrument": "EQUITY",
		            "tradedPrice": 0.0,
		            "productType": "CNC",
		            "type": 2,
		            "side": 1,
		            "pan": "****00A",
		            "discloseQty": 0,
		        }]



DEMO_POSITIONS = [{"netQty": 0, "qty": 0,
				   "avgPrice": 0, "netAvg": 0,
				   "side": 0, "productType": "INTRADAY",
				   "realized_profit": 0, "unrealized_profit": 0, "pl": 0,
				   "buyQty": 5, "buyAvg": 0,
				   "sellQty": 5, "sellAvg": 0,
				   "buyVal":0,"sellVal":0,
				   "slNo": 0, "fyToken": 0, "dummy": "          ",
				   "crossCurrency": "N", "rbiRefRate": 1.0,
				   "qtyMulti_com": 1.0, "segment" : "E", "ltp":0,
				   "symbol": "BSE:SBIN-A", "id": "BSE:SBIN-A-INTRADAY" },
				   { "netQty": 0, "qty": 0,
				   "avgPrice": 0, "netAvg": 0,
				   "side": 0, "productType": "CNC",
				   "realized_profit": 0, "unrealized_profit": 0, "pl": 0,
				   "buyQty": 5, "buyAvg": 0,
				   "sellQty": 5, "sellAvg": 0,
				   "buyVal":0,"sellVal":0,
				   "slNo": 1, "fyToken": 0, "dummy": "          ",
				   "crossCurrency": "N", "rbiRefRate": 1.0,
				   "qtyMulti_com": 1.0, "segment" : "E", "ltp":0,
				   "symbol": "BSE:RELIANCE-A", "id": "BSE:RELIANCE-A-CNC" }]



DEMO_HOLDINGS = [
			        {
			            "exchange": "ALL",
			            "symbol": "BSE:BAJFINANCE-A",
			            "marketVal": 0,
			            "fyToken": "",
			            "id": 1,
			            "remainingQuantity": 1,
			            "symbolLtp": 0,
			            "holdingType": "T1",
			            "costPrice": 0,
			            "pl": 0,
			            "quantity": 1
			        },
			        {
			            "exchange": "ALL",
			            "symbol": "BSE:TITAN-A",
			            "marketVal": 0,
			            "fyToken": "",
			            "id": 2,
			            "remainingQuantity": 3,
			            "symbolLtp": 0,
			            "holdingType": "T1",
			            "costPrice": 0,
			            "pl": 0,
			            "quantity": 3
			        },
			        {
			            "exchange": "ALL",
			            "symbol": "BSE:ICICIBANK-A",
			            "marketVal": 0,
			            "fyToken": "",
			            "id": 3,
			            "remainingQuantity": 10,
			            "symbolLtp": 0,
			            "holdingType": "HLD",
			            "costPrice": 0,
			            "pl": 0,
			            "quantity": 10
			        },
			        {
			            "exchange": "ALL",
			            "symbol": "BSE:INFY-A",
			            "marketVal": 0,
			            "fyToken": "",
			            "id": 4,
			            "remainingQuantity": 4,
			            "symbolLtp": 0,
			            "holdingType": "HLD",
			            "costPrice": 0,
			            "pl": 0,
			            "quantity": 4
			        },
			        {
			            "exchange": "ALL",
			            "symbol": "BSE:TCS-A",
			            "marketVal": 0,
			            "fyToken": "",
			            "id": 5,
			            "remainingQuantity": 2,
			            "symbolLtp": 0,
			            "holdingType": "HLD",
			            "costPrice": 0,
			            "pl": 0,
			            "quantity": 2
			        }
			    ]