moduleName = "fy_data_defines"
try:
    from fy_base_api_keys_values import API_K_TOKENHASH, API_K_FYSYMBOLS, \
     API_K_FYSYMBOL, API_K_DATA_RESOLUTION, API_K_DATA_HISTFROM, API_K_DATA_HISTTO, \
     API_K_SEARCH_SYM, API_K_FYSYMBOL_1, API_K_CORP_DATE_FROM, API_K_CORP_DATE_TO

    from fy_base_success_error_codes import ERROR_C_INV_TOKENHASH, ERROR_C_INV_FYSYMBOLS, \
     ERROR_C_INV_FYSYMBOL, ERROR_C_INV_DATA_RESOLUTION, ERROR_C_INV_DATA_FROM, \
     ERROR_C_INV_DATA_TO, ERROR_C_INV_SEARCHSYMBOL, ERROR_C_OMS_INV_DATE_FORMAT
    
    from fy_base_success_error_messages import ERROR_M_INV_TOKENHASH, \
     ERROR_M_INV_FYSYMBOLS, ERROR_M_INV_FYSYMBOL, ERROR_M_INV_DATA_RESOLUTION, \
     ERROR_M_INV_DATA_HISTFROM, ERROR_M_INV_DATA_HISTTO, ERROR_M_INV_SEARCH_SYM, \
     ERROR_M_INV_INPUT_1

except Exception as e:
    print ("ERR : %s : Could not import : %s : %s" % (moduleName, "fy_common_*", e))

# FTP Urls
URL_REQ_NSE_SECURITY_FILE_CM = "ftp://ftpguest:FTPGUEST@ftp.connect2nse.com/common/NTNEAT/security.gz"
URL_REQ_NSE_SECURITY_FILE_FO = "ftp://faoguest:FAOGUEST@ftp.connect2nse.com/faocommon/contract.gz"
URL_REQ_NSE_SECURITY_FILE_CD = "ftp://cdsguest:CDSGUEST@ftp.connect2nse.com/cdscommon/cd_contract.gz"

URL_REQ_NSE_FREE_FLOAT_CM = "ftp://ftpguest:FTPGUEST@ftp.connect2nse.com/common/NTNEAT/FreeFloat.txt"

URL_REQ_NSE_QTY_FREEZE_CM = "ftp://ftpguest:FTPGUEST@ftp.connect2nse.com/common/NTNEAT/qty_freeze_"
URL_REQ_NSE_QTY_FREEZE_FO = "ftp://faoguest:FAOGUEST@ftp.connect2nse.com/faocommon/qtyfreeze.xls"

# Tradingview config defines
TV_CONFIG_DATA_TIMEZONE = "Asia/Kolkata"
TV_CONFIG_DATA_SUPPORTED_TIMEFRAMES_1 = ["1", "2", "3", "5", "10", "15", "20", "30", "60", "120", "240", "D", "W", "M", "12M"]
TV_CONFIG_DATA_INTRADAY_MULTIPLIERS = ["1"]
TV_CONFIG_DATA_SUPPORT_DATA_SECONDS = False
TV_CONFIG_DATA_SUPPORT_DATA_DAILY = True
TV_CONFIG_DATA_SUPPORT_DATA_WK_MNTH = False
TV_CONFIG_DATA_SUPPORT_NO_VOLUME = False
TV_CONFIG_DATA_SUPPORT_DATA_LIVE = "streaming"
TV_CONFIG_DATA_SUPPORT_INTRADAY = True
TV_CONFIG_DATA_MIN_MOV_MULTIPLIER = 100  # NOT USED
TV_CONFIG_DATA_MIN_MOV_2 = 0
TV_CONFIG_DATA_PRICESCALE_1 = 100
TV_CONFIG_DATA_PRICESCALE_2 = 10000
TV_CONFIG_DATA_SEARCH_LIMIT = 100
TV_CONFIG_DATA_POINT_VALUE = 1
TV_CONFIG_DATA_HAS_EMPTY_BARS = False
TV_CONFIG_DATA_SUPPORT_SEARCH = True
TV_CONFIG_DATA_SUPPORT_GROUP_REQUEST = False
TV_CONFIG_DATA_SUPPORT_MARKS = False
TV_CONFIG_DATA_SUPPORT_TIMESCALE_MARKS = False
TV_CONFIG_DATA_SUPPORT_TIME = True

# Exchange Segment trading timings
TV_CONFIG_SESSION_TIME_CM = "0915-1530"
TV_CONFIG_SESSION_TIME_FO = "0915-1530"
TV_CONFIG_SESSION_TIME_CD = "0900-1700"

# Mandatory input dictionary

API_K_DICT_DATA_GET_QUOTE = {API_K_TOKENHASH: [ERROR_C_INV_TOKENHASH, ERROR_M_INV_TOKENHASH],
                             API_K_FYSYMBOLS: [ERROR_C_INV_FYSYMBOLS, ERROR_M_INV_FYSYMBOLS]}

API_K_DICT_DATA_GET_HIST_DATA = {API_K_TOKENHASH: [ERROR_C_INV_TOKENHASH, ERROR_M_INV_TOKENHASH],
                                 API_K_FYSYMBOL: [ERROR_C_INV_FYSYMBOL, ERROR_M_INV_FYSYMBOL],
                                 API_K_DATA_RESOLUTION: [ERROR_C_INV_DATA_RESOLUTION, ERROR_M_INV_DATA_RESOLUTION],
                                 API_K_DATA_HISTFROM: [ERROR_C_INV_DATA_FROM, ERROR_M_INV_DATA_HISTFROM],
                                 API_K_DATA_HISTTO: [ERROR_C_INV_DATA_TO, ERROR_M_INV_DATA_HISTTO]}

API_K_DICT_DATA_SYM_SEARCH = {API_K_TOKENHASH: [ERROR_C_INV_TOKENHASH, ERROR_M_INV_TOKENHASH],
                              API_K_SEARCH_SYM: [ERROR_C_INV_SEARCHSYMBOL, ERROR_M_INV_SEARCH_SYM]}

API_K_DICT_DATA_SYM_ONLY = {API_K_TOKENHASH: [ERROR_C_INV_TOKENHASH, ERROR_M_INV_TOKENHASH],
                            API_K_FYSYMBOL_1: [ERROR_C_INV_FYSYMBOL, ERROR_M_INV_FYSYMBOL]}

# Corp Action
API_K_DICT_DATA_CORP_ACTION = {API_K_FYSYMBOL: [ERROR_C_INV_FYSYMBOL, ERROR_M_INV_FYSYMBOL],
                               API_K_CORP_DATE_FROM: [ERROR_C_OMS_INV_DATE_FORMAT, ERROR_M_INV_INPUT_1],
                               API_K_CORP_DATE_TO: [ERROR_C_OMS_INV_DATE_FORMAT, ERROR_M_INV_INPUT_1]}

