try:
	from fy_base_success_error_codes import *
	from fy_base_success_error_messages import *
	from fy_base_api_keys_values import *
	# from fy_common_defines import *
	from fy_common_api_keys_values import *
except Exception as e:
	print ("ERR : %s : Could not import : %s : %s"%("fy_trading_defines","fy_common_*",e))

# Trading related URLs
URL_WEB_TRADE = "https://trade.fyers.in"
URL_DATAFEED  = "https://data.fyers.in"
URL_MOBILECHARTS = "https://mobilecharts.fyers.in"
URL_30DAYCHALLENGE = "https://30-day-challenge.fyers.in"

# Path which needs to be appended to the necessary url
PATH_CDN_LIB_1 			= "https://clib.fyers.in"
PATH_CHARTING_LIBRARY_1 = "lib/tvclib/1.14.4"
PATH_JS_DATAFEED_FOLDER = "8.7"
PATH_JS_TRADING_FOLDER  = "9.23"
ORDER_DET_VERSION_JS = "1.1" ## beta
ORDER_DET_VERSION_STYLE = "1.0" ## beta
PATH_JS_ORDER_DET_FOLDER = PATH_CDN_LIB_1+ "/trading/orddetail/js/" + ORDER_DET_VERSION_JS
PATH_CSS_ORDER_DET_FOLDER = PATH_CDN_LIB_1+ "/trading/orddetail/style/" + ORDER_DET_VERSION_STYLE
POSITION_CONV_VERSION_JS = "1.0" ## Live - 1.0
POSITION_CONV_VERSION_STYLE = "1.0"
PATH_JS_POS_CONV_FOLDER = PATH_CDN_LIB_1 + "/trading/posconv/js/" + POSITION_CONV_VERSION_JS
PATH_CSS_POS_CONV_FOLDER = PATH_CDN_LIB_1 + "/trading/posconv/style/" + POSITION_CONV_VERSION_STYLE
PATH_ORDWIN_JS_FOLDER 	= PATH_CDN_LIB_1+ "/trading/ordwin/js/1.9"
PATH_ORDWIN_STYLE_FOLDER 	= PATH_CDN_LIB_1 + "/trading/ordwin/style/1.2"
PATH_JS_DATAFEED_MOB_FOLDER = "7.2.2"

# OMS REQUEST URLS
REQ_URL_OMS_MAIN_1 = "http://internal-Fyers-Internal-Loadbalancer-2106555724.ap-south-1.elb.amazonaws.com/RupeeSeedWS/"
REQ_URL_OMS_MAIN_2 = "http://internal-fyers-internal-loadbalancer-2-447028652.ap-south-1.elb.amazonaws.com/RupeeSeedWS/" ##Read Endpoint
REQ_URL_OMS_MAIN_3 = "http://internal-Fyers-Internal-Loadbalancer-3-579587051.ap-south-1.elb.amazonaws.com/RupeeSeedWS/" ##Auth Endpoint

# REQ_URL_OMS_MAIN_1 = "https://tradeonline-pub.fyers.in/RupeeSeedWS/"
# REQ_URL_OMS_MAIN_2 = "https://tradeonline-read.fyers.in/RupeeSeedWS/"
# REQ_URL_OMS_MAIN_2 = "https://tradeonline-pub.fyers.in/RupeeSeedWS/"
# REQ_URL_OMS_MAIN_3 = "https://tradeonline-auth.fyers.in/RupeeSeedWS/"

# REQ_URL_OMS_MAIN_1 						= "http://tradeonline-uat.fyers.in:8080/RupeeSeedWS/"
# REQ_URL_OMS_MAIN_1 					= "http://13.126.15.134:8080/RupeeSeedWS/"
# REQ_URL_OMS_MAIN_1 					= "http://180.179.25.24:8080/RupeeSeedWS/"
REQ_URL_OMS_MAIN_RESETUSER 			= "http://45.112.18.5/RupeeSeedWS/resetPassword/"
REQ_URL_OMS_MAIN_FT 				= "http://45.112.18.4/GService/Service1.asmx/SendFTRequest"
REQ_URL_OMS_UAT1					= "http://180.179.25.24:8080/RupeeSeedWS/"

REQ_URL_OMS_UAT2					= "http://13.126.15.134:8080/RupeeSeedWS/"
# REQ_URL_OMS_MAIN_1					= "http://13.126.15.134:8080/RupeeSeedWS/"

# OMS REQUEST URL PATHS
API_OMS_REQ_PATH_USER_AUTH 			= "authenticate/index"
API_OMS_REQ_PATH_USER_PWD_AUTH 		= "PasswordAuth/index"
API_OMS_REQ_PATH_USER_FORGOT_PWD 	= "ForgotPassword/index"
API_OMS_REQ_PATH_USER_PWD_CHANGE 	= "changepassword"
API_OMS_REQ_PATH_USER_UNLOCK 		= "UnblockUser/index"
API_OMS_REQ_PATH_USER_LOGOUT 		= "Signout"
API_OMS_REQ_PATH_FUNDS 				= "fundlimit/index"
API_OMS_REQ_PATH_FUNDS_LIMIT_DET    = "Fundlimit/limitDetails"
API_OMS_REQ_PATH_ORDER_PLACE 		= "orderEntry/index"
API_OMS_REQ_PATH_ORDER_MODIFY	 	= "modifyOrder/index"
API_OMS_REQ_PATH_ORDER_CANCEL 		= "cancelOrder/index"
API_OMS_REQ_PATH_ORDER_BOOK 		= "orderbook/index"
API_OMS_REQ_PATH_ORDER_DETAILS 		= "orderdetails/index"
API_OMS_REQ_PATH_TRADES 			= "tradebook/index"
API_OMS_REQ_PATH_POSITIONS 			= "Netposition/index"
API_OMS_REQ_PATH_HOLDINGS 			= "holdingdetails/index"
API_OMS_REQ_PATH_CONVERT_POSITION 	= "ConvtoDel/index"
API_OMS_REQ_PATH_MARKET_STATUS 		= "MarketStatusDisplay/index"
API_OMS_REQ_PATH_CO_PLACE 			= "CoOrderEntry/Index"
API_OMS_REQ_PATH_CO_MODIFY 			= "CoModifyOrder/Index"
API_OMS_REQ_PATH_CO_EXIT 			= "CoExitOrder/Index"
# API_OMS_REQ_PATH_FT_INWARD	 	 	= "GetFundTransfer/index"
# API_OMS_REQ_PATH_FT_INWARD	 	 	= "PayIn/atom" ## Change 2019-08-02
API_OMS_REQ_PATH_FT_INWARD	 	 	= "PayIn/" ## Change 2021-01-19
API_OMS_REQ_PATH_FT_OUTWARD			= "PayOut/payoutResp"
# API_OMS_REQ_PATH_FT_OUTWARD			= "PayStatus/PayOut"
API_OMS_REQ_PATH_FT_DETAILS			= "requestpayoutdetails/index"
API_OMS_REQ_PATH_SPAN_CALC			= "SpanCalculator/index"
API_OMS_REQ_PATH_SPAN_MARG_CALC  	= "GetMarginCalculator/index"
API_OMS_REQ_PATH_BANK_DETAILS 	 	= "GetBankDetails/index"
API_OMS_REQ_PATH_WATCHLIST_NAMES 	= "watchList/getWLLstNames"
API_OMS_REQ_PATH_WATCHLIST_DETAILS 	= "watchList/getWLDetails"
API_OMS_REQ_PATH_WATCHLIST_RENAME 	= "watchList/renameWL"
API_OMS_REQ_PATH_WATCHLIST_DELETE_SYM 	= "watchList/delSymFrmWL"
API_OMS_REQ_PATH_WATCHLIST_DELETE_1 = "watchList/delWL"
API_OMS_REQ_PATH_WATCHLIST_ADD_SYM  = "watchList/addMktWatchStock"
API_OMS_REQ_PATH_WATCHLIST_CREATE  	= "watchList/createWL"
API_OMS_REQ_PATH_BO_PLACE 			= "BoOrderEntry/Index"
API_OMS_REQ_PATH_BO_MODIFY 			= "BoModifyOrder/Index"
API_OMS_REQ_PATH_BO_EXIT 			= "BoExitOrder/Index"
API_OMS_REQ_PATH_BO_ORDERBOOK 		= "BoOrderbook/index"
API_OMS_REQ_PATH_SIMPLIFIED_REGISTER = "SimplifiedReg/registerNow"
API_OMS_REQ_PATH_MARGIN_CALC       = "KnowYourMargin/CalOrdMrg"
API_OMS_REQ_PATH_SIMP_REG_GET 		= "SimplifiedReg/getDetails"
API_OMS_REQ_PATH_SIMP_REG_DEL 		= "SimplifiedReg/SimpDelete"
API_OMS_REQ_PATH_SIMP_REG_VERIFY	= "SimplifiedReg/VerifyPassword"


# Mandatory inputs at the time of calling trading api
API_K_DICT_PWD_CHANGE 	= {API_K_FYERSID:[ERROR_C_INV_FYERSID,ERROR_M_INV_FYERSID_1],
							API_K_PWD_EXIST:[ERROR_C_INV_EXISTPWD,ERROR_M_INV_EXIST_PWD],
							API_K_PWD_NEW:[ERROR_C_INV_NEWPWD,ERROR_M_INV_NEW_PWD]}

API_K_DICT_PWD_CHANGE2 = {API_K_FYERSID: [ERROR_C_INV_FYERSID, ERROR_M_INV_FYERSID_1],
							 API_K_PWD_NEW: [ERROR_C_INV_NEWPWD, ERROR_M_INV_NEW_PWD]}

API_K_DICT_USER_UNLOCK  = {API_K_FYERSID:[ERROR_C_INV_FYERSID,ERROR_M_INV_FYERSID_1],
						   API_K_EMAIL_1:[ERROR_C_INV_EMAIL,ERROR_M_INV_EMAIL],
							API_K_PAN:[ERROR_C_INV_PAN,ERROR_M_INV_PAN]}

API_K_DICT_USER_LOGIN 	= {API_K_FYERSID:[ERROR_C_INV_FYERSID,ERROR_M_INV_FYERSID_1],
							API_K_PWD_EXIST:[ERROR_C_INV_EXISTPWD,ERROR_M_INV_EXIST_PWD],
							API_K_PWD2:[ERROR_C_INV_PWD2,ERROR_M_INV_PWD2],
							API_K_APPID:[ERROR_C_INV_APPID,ERROR_M_INV_APPID],
							API_K_SECRETKEY:[ERROR_C_INV_SECRET_KEY,ERROR_M_INV_SECRETKEY]}

API_K_DICT_ORDER_ID 	= {API_K_COOKIE:[ERROR_C_INV_COOKIE,ERROR_M_INV_COOKIE],
							API_K_ORDER_ID:[ERROR_C_INV_ORDER_ID,ERROR_M_INV_ORDER_ID]}

API_K_DICT_FT 			= {API_K_COOKIE: [ERROR_C_INV_COOKIE, ERROR_M_INV_COOKIE],
							API_K_BANK_ACC: [ERROR_C_OMS_INV_BANKAC, ERROR_M_INV_BANKACC],
							API_K_FT_AMT: [ERROR_C_OMS_INV_FT_LESS_THAN_MIN, ERROR_M_INV_FT_AMT]}

API_K_DICT_ORDER_PLACE  = {API_K_COOKIE: [ERROR_C_INV_COOKIE, ERROR_M_INV_COOKIE],
							API_K_SYMBOL: [ERROR_C_INV_SYMBOL, ERROR_M_INV_FYSYMBOL],
							API_K_ORDER_QTY: [ERROR_C_INV_ORDER_QTY, ERROR_M_INV_ORDER_QTY],
							API_K_ORDER_TYPE: [ERROR_C_INV_ORDER_TYPE, ERROR_M_INV_ORDER_TYPE],
							API_K_ORDER_SIDE: [ERROR_C_INV_ORDER_SIDE, ERROR_M_INV_ORDER_SIDE],
							API_K_ORDER_PRODUCT: [ERROR_C_INV_ORDER_PRODUCT,ERROR_M_INV_ORDER_PRODUCT]}

API_K_DICT_ORDER_PLACE_GTT  = {API_K_COOKIE: [ERROR_C_INV_COOKIE, ERROR_M_INV_COOKIE],
							API_K_SYMBOL: [ERROR_C_INV_SYMBOL, ERROR_M_INV_FYSYMBOL],
							API_K_ORDER_SIDE: [ERROR_C_INV_ORDER_SIDE, ERROR_M_INV_ORDER_SIDE],
							API_K_ORDER_PRODUCT: [ERROR_C_INV_ORDER_PRODUCT,ERROR_M_INV_ORDER_PRODUCT],
							API_K_ORDER_INFO: [ERROR_C_GTT_ORDER_INFO, ERROR_M_INV_ORDER_INFO_GTT],}

API_K_DICT_ORDER_CANCEL = {API_K_COOKIE: [ERROR_C_INV_COOKIE, ERROR_M_INV_COOKIE],
							API_K_ORDER_ID: [ERROR_C_INV_ORDER_ID, ERROR_M_INV_ORDER_ID]}

API_K_DICT_ORDER_MODIFY = {API_K_COOKIE: [ERROR_C_INV_COOKIE, ERROR_M_INV_COOKIE],
							API_K_ORDER_ID: [ERROR_C_INV_ORDER_ID, ERROR_M_INV_ORDER_ID]}

API_K_DICT_ORDER_MODIFY_GTT = {API_K_COOKIE: [ERROR_C_INV_COOKIE, ERROR_M_INV_COOKIE],
							API_K_ORDER_ID: [ERROR_C_INV_ORDER_ID, ERROR_M_INV_ORDER_ID],
							API_K_ORDER_INFO: [ERROR_C_GTT_ORDER_INFO, ERROR_M_INV_ORDER_INFO_GTT]}

API_K_DICT_POPOUT_CHART = {API_K_COOKIE:[ERROR_C_INV_COOKIE,ERROR_M_INV_COOKIE],
							API_K_SYMBOL:[ERROR_C_INV_SYMBOL,ERROR_M_INV_FYSYMBOL],
							API_K_DATA_RESOLUTION:[ERROR_C_INV_DATA_RESOLUTION,ERROR_M_INV_DATA_RESOLUTION]}

# Mandatory inputs at the time of mobile login
API_K_DICT_USER_LOGIN_MOBILE 	= {API_K_FYERSID:[ERROR_C_INV_FYERSID,ERROR_M_INV_FYERSID_1],
									API_K_PWD_EXIST:[ERROR_C_INV_EXISTPWD,ERROR_M_INV_EXIST_PWD],
									API_K_PWD2:[ERROR_C_INV_PWD2,ERROR_M_INV_PWD2],
									API_K_PWD_TYPE:[ERROR_C_INV_PWD_TYPE,ERROR_M_INV_PWD_TYPE],
									API_K_IMEI_NUMBER:[ERROR_C_INV_IMEI,ERROR_M_INV_IMEI]}

API_K_DICT_USER_AUTH_MOBILE 	= {API_K_FYERSID:[ERROR_C_INV_FYERSID,ERROR_M_INV_FYERSID_1],
									API_K_IMEI_NUMBER:[ERROR_C_INV_IMEI,ERROR_M_INV_IMEI]}

# API OMS KEYS
API_OMS_K_SALT_1 			= "salt"
API_OMS_K_TOKEN_ID 			= "token_id_2"
API_OMS_K_TOKEN_ID_2 		= "rws_token_id"
API_OMS_K_TOKEN_ID_3 		= "token_id"
API_OMS_K_ENCRYPTED_DATA 	= "encrypt_data"
API_OMS_K_USER_ID 			= "user_id_2"
API_OMS_K_PASSWORD_HASH	 	= "pass"
API_OMS_K_PAN 				= "pan_no"
API_OMS_K_PAN_1 			= "pan_id"
API_OMS_K_IV_STRING 		= "iv"
API_OMS_K_REQ_SOURCE		= "source"
API_OMS_K_REQ_SOURCE_2 		= "Source"
API_OMS_K_DATA_1 			= "data"
API_OMS_K_RSA_PUB_KEY		= "pub_key"
API_OMS_K_STATUS_1 			= "status"
API_OMS_K_ERROR_CODE		= "errorcode"
API_OMS_K_CODE_1 			= "code"
API_OMS_K_MESSAGE_1			= "message"
API_OMS_K_ROW_START			= "row_1"
API_OMS_K_ROW_END 			= "row_2"
API_OMS_K_CLIENT_ID_1		= "rws_clientcode"
API_OMS_K_CLIENT_ID_2		= "client_id"
API_OMS_K_CLIENT_ID_3		= "ClientId"
API_OMS_K_CLIENT_ID_4		= "ClientCode"
API_OMS_K_EMAIL_ID 			= "email_id"
API_OMS_K_ENTITY_ID 		= "entity_id"
API_OMS_K_ENTITY_ID_2 		= "EntityId"
API_OMS_K_FLAG 				= "FLAG"
API_OMS_K_FLAG_2			= "flag"
API_OMS_ORDER_DETAIL_SEG    = "segment"

API_OMS_K_PWD_EXPIRY_DAYS	= "Passwd_Expry_Days"

# API OMS KEYS - USER DETAILS
API_OMS_K_USER_DETAILS 				= "USER_DETAIL"
API_OMS_K_USER_ID_2 				= "USERID" # NOT USED
API_OMS_K_USER_ENTITY_ID 			= "ENTITYID"
API_OMS_K_USER_UM_TYPE 				= "UM_USER_TYPE"
API_OMS_K_USER_EM_NAME 				= "EM_NAME"
API_OMS_K_USER_PROFILE_ID 			= "PROFILEID"
API_OMS_K_USER_LOGIN_ID 			= "LOGINID"
API_OMS_K_USER_PAN_1				= "PANNO"
API_OMS_K_USER_STATUS_1 			= "STATUS"
API_OMS_K_USER_DOB_1 				= "DOB"
API_OMS_K_USER_TOKEN_ID 			= "TOKENID"
API_OMS_K_USER_LAST_LOGOFF_DATE 	= "LOGOFF_DATE"
API_OMS_K_USER_EM_EXCH_CLIENT_ID	= "EM_EXCH_CLIENT_ID"
API_OMS_K_USER_EM_STATUS 			= "EM_STATUS"
API_OMS_K_USER_EMAIL_ID 			= "EMAIL_ID"
API_OMS_K_USER_LAST_LOGIN_TIME 		= "LAST_LOGIN_TIME"
API_OMS_K_USER_LAST_PWD_CHANGE 		= "LAST_PWD_CHANGE_DATE"
API_OMS_K_USER_AC_CODE 				= "ACCCODE"
API_OMS_K_USER_UM_EXCH_ALLOWED 		= "UM_EXCH_ALLOWED"
API_OMS_K_USER_UM_ENTITY_TYPE 		= "UM_ENTITY_TYPE"
API_OMS_K_USER_EM_ENTITY_MANAG_TYPE = "EM_ENTITY_MANAGER_TYPE"
API_OMS_K_USER_BANK_DETAILS 		= "bank_account_details"
## Change Ajay 2019-08-02
# API_OMS_K_USER_BANK_AC_TYPE 		= "AcctType"
API_OMS_K_USER_BANK_AC_TYPE 		= "acc_type"
# API_OMS_K_USER_BANK_AC_NUM 			= "AccNo"
API_OMS_K_USER_BANK_AC_NUM 			= "acc_no"
# API_OMS_K_USER_BANK_ID 				= "BankId"
API_OMS_K_USER_BANK_ID 				= "bank_id"
# API_OMS_K_USER_BANK_NAME 			= "BankName"
API_OMS_K_USER_BANK_NAME 			= "bank_name"
API_OMS_K_USER_BANK_NAME_MANDATE	= "BankName"
# API_OMS_K_USER_BANK_IFSC 			= "IfscCode"
API_OMS_K_USER_BANK_PAY_GW 			= "payment_gateway"
API_OMS_K_USER_BANK_IFSC 			= "ifsc"
API_OMS_K_USER_FLAGS_1 				= "flags"
API_OMS_K_USER_FLAGS_TNC 			= "TNC_FLAG"
API_OMS_K_USER_FLAGS_SUB 			= "SUBSCRIBE_FLAG"
API_OMS_K_USER_FLAGS_ACTIVATE 		= "ACTIVATE_FLAG"
# {u'allow_seg': u'CAPITAL,COMMODITY', u'bank_account_details': [{u'bank_name': u'HDFC Bank', u'ifsc': u'HDFC0000149', u'acc_no': u'50100151540162', u'acc_type': u'CAPITAL', u'bank_id': u'1006', u'payment_gateway': u'atom'}]}

API_OMS_K_POA_FLAG = "POA_FLAG"


API_OMS_K_FT_CLIENT_ID_1 	= "rp_clientid"
API_OMS_K_FT_AMOUNT 		= "amount"
API_OMS_K_FT_AMOUNT_2 		= "Amount"
API_OMS_K_FT_BANK_AC_NO 	= "acc_no"
API_OMS_K_FT_BANK_AC_NO_2 	= "account_no"
API_OMS_K_FT_BANK_AC_NO_3 	= "AccountNo"
API_OMS_K_FT_MODE 			= "payment_mode"
API_OMS_K_FT_BANK_IFSC 		= "ifsc_code"
API_OMS_K_FT_BANK_IFSC_2 	= "IfscCode"
API_OMS_K_FT_ACC_TYPE 		= "acc_type"
API_OMS_K_FT_ACC_TYPE_2		= "limit_type"

API_OMS_K_WL_NAME 		= "WL_NAME"
API_OMS_K_WL_ID 		= "WL_ID"

#Mobile login - Khyati - 20200520
API_OMS_K_SIMPLIFIED_FLAG	= "Simplyfied_flag"
API_OMS_K_PASSWORD_TYPE		= "pass_type"
API_OMS_K_IMEI_NUMBER		= "imei_no"
API_OMS_K_SIMP_PASS_FLAG	= "pass_flag"

API_OMS_V_REQ_SOURCE_MOBILE	= "M"
API_OMS_V_REQ_SOURCE_WEB	= "W"

API_OMS_K_LOGIN_ID 			= "mrm_login_id"
API_OMS_K_REG_NUMBER		= "mrm_reg_number"
API_OMS_K_IMEI_NUMBER_2		= "mrm_imei_number"
API_OMS_K_MODEL_OS 			= "mrm_model_os"
API_OMS_K_MODEL_NUMBER		= "mrm_model_number"
API_OMS_K_MODEL_OS_VER		= "mrm_model_os_ver"
API_OMS_K_PASSWORD_TYPE_2	= "mrm_pass_type"
API_OMS_K_TRANS_PASSWORD	= "mrm_transaction_pass"

# API OMS VALUES

API_OMS_REQ_TIMEOUT 		= 30
API_OMS_FT_AMT_MIN 			= 50
API_OMS_FT_AMT_MAX 			= 2500000  #Amount value changed from 1000000 to 2500000 -- 19-01-2022
API_OMS_FT_AMT_MAX_NB = 2500000
API_OMS_FT_AMT_MAX_UPI = 100000
API_OMS_FT_ACC_TYPE_CAPITAL = "CAPITAL"

# API OMS DEFAULT VALUES
API_OMS_V_DEFAULT_ORDER_OFFLINE_FLAG 	= "N"
API_OMS_V_DEFAULT_ORDER_OFFLINE_FLAG_2 	= "false"
API_OMS_V_DEFAULT_ORDER_TRIGGER_PRICE 	= 0
API_OMS_V_DEFAULT_ORDER_DISC_QTY		= 0
API_OMS_V_DEFAULT_ORDER_VALIDITY 		= "DAY"
# API_OMS_V_DEFAULT_REQ_SOURCE 			= "W"
API_OMS_V_DEFAULT_REQ_SOURCE 			= "M"
API_OMS_V_DEFAULT_FT_PAYMENT_MODE 		= "EFT"
API_OMS_V_DEFAULT_MARKET_PRO_FLAG       = "N"
API_OMS_V_DEFAULT_MARKET_PRO_VAL        = "0"
API_OMS_V_DEFAULT_GTC_FLAG              = "N"
API_OMS_V_DEFAULT_ENCASH_FLAG           = "N"

API_OMS_V_SUCCESS_1			= "success"
API_OMS_V_ERROR_1 			= "error"

API_OMS_V_PAGINATION_START 		= ""
API_OMS_V_PAGINATION_END 		= ""
API_OMS_V_EXCH_NSE 				= "NSE"
API_OMS_V_EXCH_MCX 				= "MCX"
API_OMS_V_EXCH_BSE 				= "BSE"
API_OMS_V_INST_EQUITY 			= "EQUITY" # NOT USED
API_OMS_V_SEG_CM_1 				= "E"
API_OMS_V_SEG_CM_2 				= "EQ"
API_OMS_V_SEG_FO_1 				= "D"
API_OMS_V_SEG_FO_2 				= "DR"
API_OMS_V_SEG_CD_1 				= "C"
API_OMS_V_SEG_COM_1 			= "M"
API_OMS_V_ORDER_SIDE_BUY_1 		= "B"
API_OMS_V_ORDER_SIDE_BUY_2 		= "BUY"
API_OMS_V_ORDER_SIDE_SELL_1 	= "S"
API_OMS_V_ORDER_SIDE_SELL_2	 	= "SELL"
API_OMS_V_ORDER_TYPE_LMT_1 		= "LMT"
API_OMS_V_ORDER_TYPE_LMT_2 		= "LIMIT"
API_OMS_V_ORDER_TYPE_MKT_1 		= "MKT"
API_OMS_V_ORDER_TYPE_MKT_2 		= "MARKET"
API_OMS_V_ORDER_PROD_CNC_1 		= "C"
API_OMS_V_ORDER_PROD_CNC_2 		= "CNC"
API_OMS_V_ORDER_PROD_MARGIN_1 	= "M"
API_OMS_V_ORDER_PROD_MARGIN_2 	= "MARGIN"
API_OMS_V_ORDER_PROD_INTRADAY_1	= "I"
API_OMS_V_ORDER_PROD_INTRADAY_2 = "INTRADAY"
API_OMS_V_ORDER_PROD_CO_1 		= "V"
API_OMS_V_ORDER_PROD_CO_2 		= "CO"
API_OMS_V_ORDER_PROD_BO_1 		= "B"
API_OMS_V_ORDER_PROD_BO_2 		= "BO"
API_OMS_V_PWD_SHA_HASH_TIMES 	= 1000

API_OMS_V_ORDER_LEG_VALUE_1 	= "1"
API_OMS_V_ORDER_LEG_VALUE_2 	= "2"
API_OMS_V_ORDER_LEG_VALUE_3 	= "3"


API_OMS_K_SECURITY_ID = "security_id"
API_OMS_K_PRODUCT_ID = "product_id"
API_OMS_K_TOTAL_REDEEM_QTY = "totalremqty"
API_OMS_K_PRICE = "price"
API_OMS_K_BUYSELL       = "buysell"
API_OMS_K_TRIGGER_PRICE = "trigger_price"


# Configuration for tradingview REST API
TV_CONFIG_CURRENCY_INR_1 					= "INR"
TV_CONFIG_CURRENCY_INR_SIGN 				= "Rs"
TV_CONFIG_SUPPORT_LEVEL2DATA 				= True
TV_CONFIG_SUPPORT_PRICE_LADDER 				= True
TV_CONFIG_SUPPORT_ORDER_QTY_INSTEAD_OF_AMT 	= True
TV_CONFIG_SUPPORT_ORDER_STOPLOSS_AMT 		= False
TV_CONFIG_SUPPORT_ORDER_HIST_DATA 			= True
TV_CONFIG_SUPPORT_ORDER_EDIT 				= True
TV_CONFIG_SUPPORT_ORDER_BRACKETS 			= False
TV_CONFIG_SUPPORT_POSITION_PL_UPDATE 		= False
TV_CONFIG_SUPPORT_POSITION_CLOSE 			= True
TV_CONFIG_SUPPORT_POSITION_MULTI 			= False
TV_CONFIG_SUPPORT_POSITION_REVERSE 			= False
TV_CONFIG_SUPPORT_POSITION_REDUCE 			= False

# Other trading related defines
FY_AUTH_TBL_DUMMY_VALUE_1                   = "0"

# Khyati - 20191122
BOPATH = "https://account.fyers.in/webclient/index.cfm"

API_OMS_K_FT_ACC_TYPE_3		= "Acctyp"
API_OMS_K_FT_REQ_TYPE		= "Reqtype"
API_OMS_K_FT_REQ_TYPE_2		= "req_type"
API_OMS_K_FT_ORDER_TYPE		= "OrderType"
API_OMS_K_FT_FROM_DATE		= "FromDate"
API_OMS_K_FT_TO_DATE		= "ToDate"
API_OMS_K_FT_ORDER_STATUS	= "OrderStatus"
API_OMS_K_FT_SCHEME_CODE_1	= "SchemeCode"
# API_OMS_K_FT_SCHEME_CODE_2	= "SCHEME_CODE"
API_OMS_K_FT_BUY_SELL		= "BuySell"
API_OMS_K_FT_BUY_SELL_TYPE	= "BuySellType"
API_OMS_K_FT_REQUEST_TYPE	= "RequestType"
API_OMS_K_FT_ORDER_ID		= "OrderId"
API_OMS_K_FT_QTY			= "Qty"
API_OMS_K_FT_REDEEM_ALL		= "RedeemAll"
API_OMS_K_FT_MANDATE_TYPE	= "MandateType"
API_OMS_K_FT_START_DATE		= "StartDate"
API_OMS_K_FT_END_DATE		= "EndDate"
API_OMS_K_FT_FREQUENCY		= "Frequency"
API_OMS_K_FT_INSTALLMENTS	= "Installments"
API_OMS_K_FT_FOT			= "FOT"
API_OMS_K_FT_MANDATE_ID		= "MandateId"
API_OMS_K_FT_ORDER_NO		= "OrderNo"
API_OMS_K_FT_TRANSACTION_TYPE = "TrxTyp"
API_OMS_K_FT_FOLIO_NO		= "FolioNo"
API_OMS_K_FT_PAYMENT_MODE	= "PaymentMod"
API_OMS_K_ORDER_VALIDITY	= "OrderValidity"
API_OMS_K_PAYMENT_STATUS	= "PaymentStatus"
API_OMS_K_MANDATE_IMG_BYTE	= "ImgByte"

# MF - Pragya (20200710)
# MF_REQ_URL_OMS_MAIN_1          = "https://tradeonline.fyers.in/RupeeWSMF/"
MF_REQ_URL_OMS_MAIN_1          = "http://internal-Fyers-Internal-Loadbalancer-2106555724.ap-south-1.elb.amazonaws.com/RupeeWSMF/"
# MF_REQ_URL_OMS_MAIN_1			= "http://13.126.15.134:8080/RupeeWSMF/"
# MF_REQ_URL_OMS_MAIN_1 			= "http://13.126.15.134:8080/RupeeWSMF/"
MF_REQ_URL_OMS_FUND_LIMIT		= "MfUtils/mfFundLimit"
MF_REQ_URL_OMS_ADD_FUNDS		= "MfUtils/mfAddlimit"
MF_REQ_URL_OMS_ORDER_BOOK		= "MfReport/MfOrderbook/"
MF_REQ_URL_OMS_ORDER_STATUS		= "MfReport/MfOrdStatus/"
MF_REQ_URL_OMS_PLACE_MODIFY_ORDER = "MfOrders/normal/"
MF_REQ_URL_OMS_MANDATE_BOOK		= "MfUtils/MandateOrderBook"
MF_REQ_URL_OMS_GENERATE_MANDATE_ID = "MfUtils/MandateId"
MF_REQ_URL_OMS_PLACE_CANCEL_SIP = "MfOrders/sip/"
MF_REQ_URL_OMS_GET_HOLDINGS		= "MfReport/MfHolding/"
MF_REQ_URL_OMS_ORDER_DETAILS	= "MfReport/MfOrderDetails/"
MF_REQ_URL_OMS_SIP_HISTORY		= "MfReport/MfDueReport/"
MF_REQ_URL_OMS_MANDATE_UPLOAD	= "MfMandate/MandateImageUpload"
# MF_REQ_URL_DEV					= "/fydev/v1"
# MF_REQ_URL_BANK_DETAILS			= URL_DATAFEED+MF_REQ_URL_DEV+"/fundtx/v1/bankdetails"
MANDATE_UPLOAD_SALT 			= "DRhsk123LjFGG9dscuKm245fKW3"

MF_SCHEME_CODE_RE					= r"^[A-Za-z0-9-]*$"
API_OMS_V_DEFAULT_MF_SIP_TYPE      	= "3"
API_OMS_V_DEFAULT_MF_DATE_FORMAT_1 	= "%d/%m/%Y"
API_OMS_V_DEFAULT_MF_DATE_FORMAT_2 	= "%d-%m-%Y"
API_OMS_V_DEFAULT_MF_MANDATE_TYPE	= "X"
API_OMS_V_DEFAULT_MF_MANDATE_TYPE_E_NACH = "N"


MF_APP_ID = "HWAOVY4R26"
MF_MANDATE_FIXED_AMOUNT = "100000"

MF_REQ_TYPE_ADD_FUND_LIST = ["A", "R"]
MF_SIDE_LIST = ["P", "R"]
# MF_ORDER_TYPE_LIST = ["1", "3", "ALL"]
MF_ORDER_TYPE_DICT = {"1": "normalOrder", "2": "SipOrder","3": "XSipOrder", "4": "switchOrder", "5": "spreadOrder", "6": "swpOrder",
					  "7": "stpOrder", "ALL": ""}
MF_ORDER_DETAILS_TYPE_DICT = {"1": "lumsum", "2": "sip", "3": "xsip", "4": "switch", "5": "spread", "6": "swp", "7": "stp"}
MF_BUY_SELL_TYPE_LIST = ["FRESH", "ADDITIONAL"]
MF_ORDER_STATUS_LIST = ["VALID", "INVALID"]
MF_TRANSACTION_TYPE_LIST = ["D", "P"]
MF_PAYMENT_MODE_LIST = ["L", "B"]
MF_REQUEST_TYPE_LIST = ["C", "M"]
# MF_FOT_FLAG_LIST = ["Y", "N"]
MF_ACC_TYPE_LIST = ["SB", "CB", "NE", "NO"]
MF_ORDER_VALIDITY_LIST = ["ALL", "VALID", "INVALID"]
MF_PAYMENT_STATUS_LIST = ["ALL", "P", "S"]
MF_ORDER_STATUS_ORDER_BOOK_LIST = ["ALL", "PENDING", "REJECTED", "CANCELLED", "CONFIRMED"]
MF_ORDER_TYPE_LIST = ["SIP", "XSIP", "SWP", "STP", "SWITCH", ""]
MF_RESEND_EMAIL_FLAG = ["0", "1"]
MF_MANDATE_TYPE_LIST = ["N", "X"]

API_K_MF_ADD_MF_LIMIT = {API_K_TOKENHASH: [ERROR_C_INV_TOKENHASH, ERROR_M_INV_TOKENHASH],
						 API_K_MF_AMOUNT: [ERROR_C_MF_INV_AMOUNT, ERROR_M_MF_INV_AMOUNT],
						 API_K_MF_REQ_TYPE: [ERROR_C_MF_INV_REQUEST_TYPE, ERROR_M_MF_INV_REQUEST_TYPE]}

API_K_MF_ORDER_BOOK = {API_K_TOKENHASH: [ERROR_C_INV_TOKENHASH, ERROR_M_INV_TOKENHASH],
					   API_K_MF_ORDER_TYPE: [ERROR_C_MF_INV_ORDER_TYPE, ERROR_M_INV_ORDER_TYPE],
					   API_K_MF_ORDER_VALIDITY: [ERROR_C_MF_INV_ORDER_VALIDITY, ERROR_M_MF_INV_ORDER_VALIDITY],
					   API_K_MF_PAYMENT_STATUS: [ERROR_C_MF_INV_PAYMENT_STATUS, ERROR_M_MF_INV_PAYMENT_STATUS],
					   API_K_MF_ORDER_STATUS: [ERROR_C_MF_INV_ORDER_STATUS, ERROR_M_MF_INV_ORDER_STATUS],
					   API_K_MF_SCHEME_CODE: [ERROR_C_MF_INV_SCHEME, ERROR_M_MF_INV_SCHEME]
					   }

API_K_MF_PLACE_ORDER = {API_K_TOKENHASH: [ERROR_C_INV_TOKENHASH, ERROR_M_INV_TOKENHASH],
						API_K_MF_SCHEME_CODE: [ERROR_C_MF_INV_SCHEME, ERROR_M_MF_INV_SCHEME],
						API_K_MF_SIDE: [ERROR_C_MF_INV_BUY_SELL, ERROR_M_MF_INV_BUY_SELL],
						API_K_MF_BUY_SELL_TYPE :[ERROR_C_MF_INV_BUY_SELL_TYPE, ERROR_M_MF_INV_BUY_SELL_TYPE],
						API_K_MF_QTY: [ERROR_C_MF_INV_QTY, ERROR_M_MF_INV_QTY],
						API_K_MF_AMOUNT: [ERROR_C_MF_INV_AMOUNT, ERROR_M_MF_INV_AMOUNT],
						API_K_MF_TRANSACTION_TYPE: [ERROR_C_MF_INV_TRANSACTION_TYPE, ERROR_M_MF_INV_TRANSACTION_TYPE],
						API_K_MF_PAYMENT_MODE: [ERROR_C_MF_INV_PAYMENT_MODE, ERROR_M_MF_INV_PAYMENT_MODE],
						API_K_MF_FOLIO_NO: [ERROR_C_MF_INV_FOLIO_NO, ERROR_M_MF_INV_FOLIO_NO]
						}

API_K_MF_REGISTER_MANDATE = {API_K_TOKENHASH: [ERROR_C_INV_TOKENHASH, ERROR_M_INV_TOKENHASH],
							 # API_K_MF_AMOUNT: [ERROR_C_MF_INV_AMOUNT, ERROR_M_MF_INV_AMOUNT],
							 API_K_MF_START_DATE: [ERROR_C_MF_INV_DATE, ERROR_M_MF_INV_DATE],
							 # API_K_MF_END_DATE: [ERROR_C_MF_INV_DATE, ERROR_M_MF_INV_DATE],
							 API_K_BANK_ACC: [ERROR_C_INV_BANKAC, ERROR_M_INV_BANKACC],
							 API_K_BANK_NAME: [ERROR_C_INV_BANKAC, ERROR_M_INV_BANKNAME],
							 # API_K_ACC_TYPE_1: [ERROR_C_INV_BANKDETAILS, ERROR_M_INV_BANKDETAILS],
							 API_K_BANK_IFSC: [ERROR_C_INV_BANKDETAILS, ERROR_M_INV_BANKDETAILS],
							 API_K_PHONE_NO: [ERROR_C_INV_USER_PHONE_NO, ERROR_M_INV_USER_PHONE_NO],
							 API_K_MF_MANDATE_TYPE : [ERROR_C_MF_INV_MANDATE_TYPE, ERROR_M_MF_INV_MANDATE_TYPE]
							 }

API_K_MF_PLACE_SIP_ORDER = {API_K_TOKENHASH: [ERROR_C_INV_TOKENHASH, ERROR_M_INV_TOKENHASH],
							API_K_MF_SCHEME_CODE: [ERROR_C_MF_INV_SCHEME, ERROR_M_MF_INV_SCHEME],
							API_K_MF_AMOUNT: [ERROR_C_MF_INV_AMOUNT, ERROR_M_MF_INV_AMOUNT],
							API_K_MF_FREQUENCY: [ERROR_C_MF_INV_FREQUENCY, ERROR_M_MF_INV_FREQUENCY],
							API_K_MF_INSTALLMENTS: [ERROR_C_MF_INV_INSTALLMENTS, ERROR_M_MF_INV_INSTALLMENTS],
							API_K_MF_START_DATE: [ERROR_C_MF_INV_DATE, ERROR_M_MF_INV_DATE],
							API_K_MF_MANDATE_ID: [ERROR_C_MF_INV_MANDATE_ID, ERROR_M_MF_INV_MANDATE_ID],
							# API_K_MF_FOT_FLAG: [ERROR_C_MF_INV_FOT_FLAG, ERROR_M_MF_INV_FOT_FLAG],
							API_K_MF_PAYMENT_MODE: [ERROR_C_MF_INV_PAYMENT_MODE, ERROR_M_MF_INV_PAYMENT_MODE]
							}

API_K_MF_CANCEL_SIP_ORDER = {API_K_TOKENHASH: [ERROR_C_INV_TOKENHASH, ERROR_M_INV_TOKENHASH],
							API_K_MF_SCHEME_CODE: [ERROR_C_MF_INV_SCHEME, ERROR_M_MF_INV_SCHEME],
							API_K_MF_ORDER_ID: [ERROR_C_MF_INV_ORDER_ID, ERROR_M_MF_INV_ORDER_ID]
							# API_K_MF_FOT_FLAG: [ERROR_C_MF_INV_FOT_FLAG, ERROR_M_MF_INV_FOT_FLAG]
							}

API_K_MF_EMAIL_MANDATE = {API_K_TOKENHASH: [ERROR_C_INV_TOKENHASH, ERROR_M_INV_TOKENHASH], 
							API_K_MF_MANDATE_ID: [ERROR_C_MF_INV_MANDATE_ID, ERROR_M_MF_INV_MANDATE_ID],
							API_K_EMAIL_1: [ERROR_C_INV_EMAIL, ERROR_M_INV_EMAIL],
							API_K_USER_NAME: [ERROR_C_INV_USER_NAME, ERROR_M_INV_USER_NAME],
							API_K_MF_IMG_MANDATE_DOWNLOAD: [ERROR_C_MF_INV_IMG_MADATE, ERROR_M_MF_INV_IMG_MADATE],
							API_K_MF_URL_MANDATE_UPLOAD: [ERROR_C_MF_INV_URL_MADATE, ERROR_M_MF_INV_URL_MADATE],
							API_K_MF_RESEND_EMAIL_FLAG: [ERROR_C_MF_RESEND_EMAIL_FLAG, ERROR_M_MF_RESEND_EMAIL_FLAG]}

API_K_MF_UPLOAD_MANDATE = {API_K_FYERSID: [ERROR_C_INV_FYERSID, ERROR_M_INV_FYERSID_1],
							API_K_MF_MANDATE_ID: [ERROR_C_MF_INV_MANDATE_ID, ERROR_M_MF_INV_MANDATE_ID],
							API_K_MF_TOKEN_ID: [ERROR_C_MF_INV_TOKEN_ID, ERROR_M_MF_INV_TOKEN_ID],
							API_K_MF_IMG_MANDATE_UPLOAD: [ERROR_C_MF_INV_IMG_MADATE, ERROR_M_MF_INV_IMG_MADATE],
							# API_K_MF_URL_MANDATE_UPLOAD: [ERROR_C_MF_INV_URL_MADATE, ERROR_M_MF_INV_URL_MADATE]
							}

# EDIS - 20200722

EDIS_REQ_URL_OMS_INDEX = "EDISTransaction/index"
EDIS_REQ_URL_OMS_DETAILS = "EDISTransaction/eDISdetails"
EDIS_REQ_URL_OMS_INQUIRY = "EDISTransaction/reqInquiry"
EDIS_REQ_URL_OMS_BO_TPIN_GEN = "EDISTransaction/BOTpinGen"
EDIS_REQ_TYPE_PRE_TRADE = "D"
EDIS_TOTAL_DAYS = 1
EDIS_ALREADY_AUTNETICATED_FLAG = 1
EDIS_NOT_AUTNETICATED_FLAG = 0

API_OMS_K_EXCHANE = "exch_id"
API_OMS_K_ISIN = "isin_code"
API_OMS_K_EDIS_RECORDS_LIST = "records_list"
API_OMS_K_EDIS_REQ_IDENTIFIER = "req_identifier"
API_OMS_K_EDIS_REQ_ID = "req_id"
API_OMS_K_EDIS_TOTAL_DAYS = "totaldays"
API_OMS_K_POA_FLAG = "POA_FLAG"

EDIS_REQ_IDENTIFIER_LIST = ["S", "C"]
EDIS_EXCHANGE_LIST = ["NSE", "BSE", "MCX"]

# API_K_EDIS_TRANSACTION_REQ = {API_K_TOKENHASH: [ERROR_C_INV_TOKENHASH, ERROR_M_INV_TOKENHASH], 
# 						API_K_EDIS_REQ_IDENTIFIER: [ERROR_C_EDIS_INV_REQ, ERROR_M_EDIS_INV_REQ],
# 						API_K_SEARCH_EXCH: [ERROR_C_INV_EXCHANGE, ERROR_M_INV_EXCHANGE],
# 						API_K_EDIS_RECORD_LST: [ERROR_C_EDIS_RECORD_LST, ERROR_M_EDIS_RECORD_LST]}

API_K_EDIS_TRANSACTION_REQ = {API_K_TOKENHASH: [ERROR_C_INV_TOKENHASH, ERROR_M_INV_TOKENHASH], 
						API_K_EDIS_RECORD_LST: [ERROR_C_EDIS_RECORD_LST, ERROR_M_EDIS_RECORD_LST]}

API_K_EDIS_INQUIRY_REQ = {API_K_TOKENHASH: [ERROR_C_INV_TOKENHASH, ERROR_M_INV_TOKENHASH], 
						API_K_EDIS_UNIQUE_TXN_ID: [ERROR_C_EDIS_INV_TXN_ID, ERROR_M_EDIS_INV_IXN_ID]}
# EDIS
API_OMS_K_POA_FLAG = "POA_FLAG"
API_OMS_K_BO_ID = "BO_ID"

##Push Notifications
# URL_RS_REQ	= "http://uat.rupeetracker.in/"
# URL_RS_REQ	= "http://rupeeuat.karvyonline.com/"
URL_RS_REQ = "http://103.14.188.116/"
PATH_RS_LOGIN_REQ	= "PushNoti/api/PN/PushNReq"

FREEZE_QTY_NIFTY = 1800
FREEZE_QTY_BANKNIFTY = 1200
FREEZE_QTY_FINNIFTY = 1800

# FREEZE_QTY_NIFTY = 50
# FREEZE_QTY_BANKNIFTY = 25
# FREEZE_QTY_FINNIFTY = 40
