WATCHLIST_UPDATE_TYPE_ADD_SINGLE     = 1
WATCHLIST_UPDATE_TYPE_REMOVE_SINGLE  = 2
WATCHLIST_UPDATE_TYPE_ADD_MULTIPLE   = 3
WATCHLIST_UPDATE_TYPE_REMOVE_MULTIPLE = 4
WATCHLIST_UPDATE_TYPE_ENTIRE_LIST    = 5
WATCHLIST_UPDATE_TYPE_RENAME         = 6

WATCHLIST_MAXIMUM_NUMBER_SYMBOLS     = 52
WATCHLIST_MAX_INPUT_SIZE             = 1
WATCHLIST_MAX_SIZE                   = 50

WATCHLIST_PREDEFINED_ID_STARTSWITH = "predefined_"
WATCHLIST_PREDEFINED_NAME_STARTSWITH = "- "
WATCHLIST_CUSTOM_NAME_STARTSWITH = " "

# Creation of Fno predefined watchlists
WATCHLIST_PREDEFINED_FNO_UNDERLYING_FYTOKENS = [(101000000026000,2,0,"Nifty Near Month Expiry","NSE:NIFTY50-INDEX"),(101000000026009,2,0,"Banknifty Near Month Expiry","NSE:NIFTYBANK-INDEX"),(101000000026009,1,0,"Banknifty Near Week Expiry","NSE:NIFTYBANK-INDEX"),(101000000026009,1,1,"Banknifty Next Week Expiry","NSE:NIFTYBANK-INDEX"),(101000000026000,1,0,"Nifty Near Week Expiry","NSE:NIFTY50-INDEX"),(101000000026000,1,1,"Nifty Next Week Expiry","NSE:NIFTY50-INDEX")]

# Default watchlists names
WATCHLIST_PREDEFINED_NAME_NIFTY50           = "Nifty 50"
WATCHLIST_PREDEFINED_NAME_NIFTYBANK         = "Nifty Bank"
WATCHLIST_PREDEFINED_NAME_NIFTYNEXT50       = "Nifty Next 50"
WATCHLIST_PREDEFINED_NAME_NIFTYIT           = "Nifty IT"
WATCHLIST_PREDEFINED_NAME_NIFTYPHARMA       = "Nifty Pharma"
WATCHLIST_PREDEFINED_NAME_NIFTYPRIVATEBANK  = "Nifty Private Bank"
WATCHLIST_PREDEFINED_NAME_NIFTYPSUBANK      = "Nifty PSU Bank"
WATCHLIST_PREDEFINED_NAME_NIFTYFINANCIAL    = "Nifty Financials"
WATCHLIST_PREDEFINED_NAME_NIFTYAUTO         = "Nifty Auto"
WATCHLIST_PREDEFINED_NAME_NIFTYFMCG         = "Nifty FMCG"
WATCHLIST_PREDEFINED_NAME_NIFTYMEDIA        = "Nifty Media"
WATCHLIST_PREDEFINED_NAME_NIFTYREALTY       = "Nifty Realty"
WATCHLIST_PREDEFINED_NAME_NIFTYMETALS       = "Nifty Metals"
WATCHLIST_PREDEFINED_NAME_NIFTYINDICES      = "Nifty Indices"
WATCHLIST_PREDEFINED_NAME_NIFTYCOMMODITIES  = "Nifty Commodities"
WATCHLIST_PREDEFINED_NAME_NIFTYENERGY       = "Nifty Energy"
WATCHLIST_PREDEFINED_NAME_NIFTYINFRA        = "Nifty Infra"
WATCHLIST_PREDEFINED_NAME_NIFTYMIDCAP50     = "Nifty Midcap 50"
WATCHLIST_PREDEFINED_NAME_MCXFUTCOM         = "MCX Near Futures"
WATCHLIST_PREDEFINED_NAME_CURFUT            = "Currency Near Futures"
WATCHLIST_PREDEFINED_NAME_NIFTYFUT          = "Nifty Near Futures"
WATCHLIST_PREDEFINED_NAME_BANKNIFTYFUT      = "BankNifty Near Futures"
#newly added - Rushbh 1648030070
WATCHLIST_PREDEFINED_NAME_NIFTYOILGAS       = "Nifty Oil and Gas"
WATCHLIST_PREDEFINED_NAME_NIFTYHEALTHCARE   = "Nifty Healthcare"

# Default watchlists symbols
WATCHLIST_PREDEFINED_SYMBOLS_NIFTY50 = ["NSE:NIFTY50-INDEX", "NSE:ADANIPORTS-EQ", "NSE:ASIANPAINT-EQ", "NSE:AXISBANK-EQ", "NSE:BAJAJ-AUTO-EQ", "NSE:BAJFINANCE-EQ", "NSE:BAJAJFINSV-EQ", "NSE:BPCL-EQ", "NSE:BHARTIARTL-EQ", "NSE:INFRATEL-EQ", "NSE:BRITANNIA-EQ", "NSE:CIPLA-EQ", "NSE:COALINDIA-EQ", "NSE:DRREDDY-EQ", "NSE:EICHERMOT-EQ", "NSE:GAIL-EQ", "NSE:GRASIM-EQ", "NSE:HCLTECH-EQ", "NSE:HDFCBANK-EQ", "NSE:HEROMOTOCO-EQ", "NSE:HINDALCO-EQ", "NSE:HINDUNILVR-EQ", "NSE:HDFC-EQ", "NSE:ICICIBANK-EQ", "NSE:ITC-EQ", "NSE:IBULHSGFIN-EQ", "NSE:IOC-EQ", "NSE:INDUSINDBK-EQ", "NSE:INFY-EQ", "NSE:JSWSTEEL-EQ", "NSE:KOTAKBANK-EQ", "NSE:LT-EQ", "NSE:M&M-EQ", "NSE:MARUTI-EQ", "NSE:NTPC-EQ", "NSE:ONGC-EQ", "NSE:POWERGRID-EQ", "NSE:RELIANCE-EQ", "NSE:SBIN-EQ", "NSE:SUNPHARMA-EQ", "NSE:TCS-EQ", "NSE:TATAMOTORS-EQ", "NSE:TATASTEEL-EQ", "NSE:TECHM-EQ", "NSE:TITAN-EQ", "NSE:UPL-EQ", "NSE:ULTRACEMCO-EQ", "NSE:VEDL-EQ", "NSE:WIPRO-EQ", "NSE:YESBANK-EQ", "NSE:ZEEL-EQ"]

WATCHLIST_PREDEFINED_SYMBOLS_NIFTYBANK = ["NSE:NIFTYBANK-INDEX", "NSE:AXISBANK-EQ","NSE:BANKBARODA-EQ", "NSE:FEDERALBNK-EQ","NSE:HDFCBANK-EQ","NSE:ICICIBANK-EQ","NSE:IDFCFIRSTB-EQ","NSE:INDUSINDBK-EQ","NSE:KOTAKBANK-EQ","NSE:PNB-EQ", "NSE:RBLBANK-EQ", "NSE:SBIN-EQ","NSE:YESBANK-EQ"]

WATCHLIST_PREDEFINED_SYMBOLS_NIFTYNEXT50 = ["NSE:NIFTYNEXT50-INDEX", "NSE:ABB-EQ","NSE:ABCAPITAL-EQ","NSE:ACC-EQ","NSE:AMBUJACEM-EQ","NSE:ASHOKLEY-EQ","NSE:AUROPHARMA-EQ","NSE:BANKBARODA-EQ","NSE:BEL-EQ","NSE:BHEL-EQ","NSE:BOSCHLTD-EQ","NSE:CADILAHC-EQ","NSE:COLPAL-EQ","NSE:CONCOR-EQ","NSE:CUMMINSIND-EQ","NSE:DABUR-EQ","NSE:DLF-EQ","NSE:DMART-EQ","NSE:EMAMILTD-EQ","NSE:GICRE-EQ","NSE:GODREJCP-EQ","NSE:HAVELLS-EQ","NSE:HINDZINC-EQ","NSE:ICICIPRULI-EQ","NSE:IDEA-EQ","NSE:INDIGO-EQ","NSE:JSWSTEEL-EQ","NSE:L&TFH-EQ","NSE:LICHSGFIN-EQ","NSE:MARICO-EQ","NSE:MCDOWELL-N-EQ","NSE:MOTHERSUMI-EQ","NSE:MRF-EQ","NSE:NHPC-EQ","NSE:NMDC-EQ","NSE:OFSS-EQ","NSE:OIL-EQ","NSE:PEL-EQ","NSE:PETRONET-EQ","NSE:PFC-EQ","NSE:PGHH-EQ","NSE:PIDILITIND-EQ","NSE:PNB-EQ","NSE:RECLTD-EQ","NSE:SAIL-EQ","NSE:SBILIFE-EQ","NSE:SHREECEM-EQ","NSE:SIEMENS-EQ","NSE:SRTRANSFIN-EQ","NSE:SUNTV-EQ"]

WATCHLIST_PREDEFINED_SYMBOLS_NIFTYIT = ["NSE:NIFTYIT-INDEX", "NSE:HCLTECH-EQ","NSE:INFIBEAM-EQ","NSE:INFY-EQ","NSE:MINDTREE-EQ","NSE:NIITTECH-EQ","NSE:OFSS-EQ","NSE:TCS-EQ","NSE:TATAELXSI-EQ","NSE:TECHM-EQ","NSE:WIPRO-EQ"]

WATCHLIST_PREDEFINED_SYMBOLS_NIFTYPHARMA = ["NSE:NIFTYPHARMA-INDEX","NSE:AUROPHARMA-EQ","NSE:BIOCON-EQ","NSE:CADILAHC-EQ","NSE:CIPLA-EQ","NSE:DIVISLAB-EQ","NSE:DRREDDY-EQ","NSE:GLENMARK-EQ","NSE:LUPIN-EQ","NSE:PEL-EQ","NSE:SUNPHARMA-EQ"]

WATCHLIST_PREDEFINED_SYMBOLS_NIFTYPRIVATEBANK = ["NSE:NIFTYPVTBANK-INDEX", "NSE:AXISBANK-EQ","NSE:FEDERALBNK-EQ","NSE:HDFCBANK-EQ","NSE:ICICIBANK-EQ","NSE:IDFCFIRSTB-EQ","NSE:INDUSINDBK-EQ","NSE:KOTAKBANK-EQ","NSE:RBLBANK-EQ","NSE:SOUTHBANK-EQ","NSE:YESBANK-EQ"]

WATCHLIST_PREDEFINED_SYMBOLS_NIFTYPSUBANK = ["NSE:NIFTYPSUBANK-INDEX", "NSE:ALBK-EQ","NSE:ANDHRABANK-EQ","NSE:BANKBARODA-EQ","NSE:BANKINDIA-EQ","NSE:CANBK-EQ","NSE:IDBI-EQ","NSE:INDIANB-EQ","NSE:ORIENTBANK-EQ","NSE:PNB-EQ","NSE:SBIN-EQ","NSE:SYNDIBANK-EQ","NSE:UNIONBANK-EQ"]

WATCHLIST_PREDEFINED_SYMBOLS_NIFTYFINANCIAL = ["NSE:NIFTYFINSERVICE-INDEX", "NSE:AXISBANK-EQ","NSE:BAJFINANCE-EQ","NSE:BAJAJFINSV-EQ","NSE:BAJAJHLDNG-EQ","NSE:HDFCBANK-EQ","NSE:HDFC-EQ","NSE:ICICIBANK-EQ","NSE:KOTAKBANK-EQ","NSE:LICHSGFIN-EQ","NSE:M&MFIN-EQ","NSE:PFC-EQ","NSE:RECLTD-EQ","NSE:SRTRANSFIN-EQ","NSE:SBIN-EQ"]

WATCHLIST_PREDEFINED_SYMBOLS_NIFTYAUTO = ["NSE:NIFTYAUTO-INDEX", "NSE:AMARAJABAT-EQ","NSE:APOLLOTYRE-EQ","NSE:ASHOKLEY-EQ","NSE:BAJAJ-AUTO-EQ","NSE:BHARATFORG-EQ","NSE:BOSCHLTD-EQ","NSE:EICHERMOT-EQ","NSE:EXIDEIND-EQ","NSE:HEROMOTOCO-EQ","NSE:MRF-EQ","NSE:M&M-EQ","NSE:MARUTI-EQ","NSE:MOTHERSUMI-EQ","NSE:TVSMOTOR-EQ","NSE:TATAMTRDVR-EQ","NSE:TATAMOTORS-EQ"]

WATCHLIST_PREDEFINED_SYMBOLS_NIFTYFMCG = ["NSE:NIFTYFMCG-INDEX", "NSE:BRITANNIA-EQ","NSE:COLPAL-EQ","NSE:DABUR-EQ","NSE:EMAMILTD-EQ","NSE:GSKCONS-EQ","NSE:GODREJCP-EQ","NSE:GODREJIND-EQ","NSE:HINDUNILVR-EQ","NSE:ITC-EQ","NSE:JUBLFOOD-EQ","NSE:MARICO-EQ","NSE:PGHH-EQ","NSE:TATAGLOBAL-EQ","NSE:UBL-EQ","NSE:MCDOWELL-N-EQ"]

WATCHLIST_PREDEFINED_SYMBOLS_NIFTYMEDIA = ["NSE:NIFTYMEDIA-INDEX", "NSE:DBCORP-EQ","NSE:DEN-EQ","NSE:DISHTV-EQ","NSE:EROSMEDIA-EQ","NSE:HTMEDIA-EQ","NSE:HATHWAY-EQ","NSE:INOXLEISUR-EQ","NSE:JAGRAN-EQ","NSE:NAVNETEDUL-EQ","NSE:NETWORK18-EQ","NSE:PVR-EQ","NSE:SUNTV-EQ","NSE:TVTODAY-EQ","NSE:TV18BRDCST-EQ","NSE:ZEEL-EQ"]

WATCHLIST_PREDEFINED_SYMBOLS_NIFTYREALTY = ["NSE:NIFTYREALTY-INDEX", "NSE:BRIGADE-EQ","NSE:DLF-EQ","NSE:GODREJPROP-EQ","NSE:HDIL-EQ","NSE:IBREALEST-EQ","NSE:OBEROIRLTY-EQ","NSE:PHOENIXLTD-EQ","NSE:PRESTIGE-EQ","NSE:SOBHA-EQ","NSE:UNITECH-EQ"]

WATCHLIST_PREDEFINED_SYMBOLS_NIFTYMETALS = ["NSE:NIFTYMETAL-INDEX", "NSE:APLAPOLLO-EQ","NSE:COALINDIA-EQ","NSE:HINDALCO-EQ","NSE:HINDCOPPER-EQ","NSE:HINDZINC-EQ","NSE:JSWSTEEL-EQ","NSE:JSLHISAR-EQ","NSE:JINDALSTEL-EQ","NSE:MOIL-EQ","NSE:NMDC-EQ","NSE:NATIONALUM-EQ","NSE:SAIL-EQ","NSE:TATASTEEL-EQ","NSE:VEDL-EQ","NSE:WELCORP-EQ"]

WATCHLIST_PREDEFINED_SYMBOLS_NIFTYINDICES = ["NSE:NIFTY50-INDEX","NSE:NIFTYIT-INDEX","NSE:NIFTYBANK-INDEX","NSE:NIFTYMIDCAP50-INDEX","NSE:INDIAVIX-INDEX","NSE:NIFTYINFRA-INDEX","NSE:NIFTYPSE-INDEX","NSE:NIFTY100-INDEX","NSE:NIFTY200-INDEX","NSE:NIFTY500-INDEX","NSE:NIFTYAUTO-INDEX","NSE:NIFTYCOMMODITIES-INDEX","NSE:NIFTYCONSUMPTION-INDEX","NSE:NIFTYDIVOPPS50-INDEX","NSE:NIFTYENERGY-INDEX","NSE:NIFTYFINSERVICE-INDEX","NSE:NIFTYFMCG-INDEX","NSE:NIFTYGROWSECT15-INDEX","NSE:NIFTYGS10YR-INDEX","NSE:NIFTYGS10YRCLN-INDEX","NSE:NIFTYGS1115YR-INDEX","NSE:NIFTYGS15YRPLUS-INDEX","NSE:NIFTYGS48YR-INDEX","NSE:NIFTYGS813YR-INDEX","NSE:NIFTYGSCOMPSITE-INDEX","NSE:NIFTYMEDIA-INDEX","NSE:NIFTYMETAL-INDEX","NSE:NIFTYMIDLIQ15-INDEX","NSE:NIFTYMIDCAP100-INDEX","NSE:NIFTYMNC-INDEX","NSE:NIFTYNEXT50-INDEX","NSE:NIFTYPHARMA-INDEX","NSE:NIFTYPSUBANK-INDEX","NSE:NIFTYPVTBANK-INDEX","NSE:NIFTYQUALITY30-INDEX","NSE:NIFTYREALTY-INDEX","NSE:NIFTYSERVSECTOR-INDEX","NSE:NIFTYSMLCAP100-INDEX","NSE:NIFTY100LIQ15-INDEX","NSE:NIFTY50DIVPOINT-INDEX","NSE:NIFTY50PR1XINV-INDEX","NSE:NIFTY50PR2XLEV-INDEX","NSE:NIFTY50TR1XINV-INDEX","NSE:NIFTY50TR2XLEV-INDEX","NSE:NIFTY50VALUE20-INDEX","NSE:NIFTY ALPHA 50-INDEX"]

WATCHLIST_PREDEFINED_SYMBOLS_NIFTYCOMMODITIES = ["NSE:NIFTYCOMMODITIES-INDEX", "NSE:ACC-EQ","NSE:AMBUJACEM-EQ","NSE:BPCL-EQ","NSE:CENTURYTEX-EQ","NSE:COALINDIA-EQ","NSE:DALMIABHA-EQ","NSE:GRASIM-EQ","NSE:HINDALCO-EQ","NSE:HINDPETRO-EQ","NSE:HINDZINC-EQ","NSE:IOC-EQ","NSE:JSWSTEEL-EQ","NSE:NHPC-EQ","NSE:NMDC-EQ","NSE:NTPC-EQ","NSE:ONGC-EQ","NSE:OIL-EQ","NSE:PIIND-EQ","NSE:PIDILITIND-EQ","NSE:RELIANCE-EQ","NSE:RELINFRA-EQ","NSE:SHREECEM-EQ","NSE:SAIL-EQ","NSE:TATACHEM-EQ","NSE:TATAPOWER-EQ","NSE:TATASTEEL-EQ","NSE:RAMCOCEM-EQ","NSE:UPL-EQ","NSE:ULTRACEMCO-EQ","NSE:VEDL-EQ"]

WATCHLIST_PREDEFINED_SYMBOLS_NIFTYMNC = ["NSE:ABB-EQ","NSE:AMBUJACEM-EQ","NSE:ASHOKLEY-EQ","NSE:BOSCHLTD-EQ","NSE:BRITANNIA-EQ","NSE:CASTROLIND-EQ","NSE:COLPAL-EQ","NSE:CUMMINSIND-EQ","NSE:GSKCONS-EQ","NSE:HINDUNILVR-EQ","NSE:MARUTI-EQ","NSE:OFSS-EQ","NSE:SIEMENS-EQ","NSE:MCDOWELL-N-EQ","NSE:VEDL-EQ"]

WATCHLIST_PREDEFINED_SYMBOLS_NIFTYENERGY = ["NSE:NIFTYENERGY-INDEX", "NSE:BPCL-EQ","NSE:GAIL-EQ","NSE:HINDPETRO-EQ","NSE:IOC-EQ","NSE:NTPC-EQ","NSE:ONGC-EQ","NSE:POWERGRID-EQ","NSE:RELIANCE-EQ","NSE:RELINFRA-EQ","NSE:TATAPOWER-EQ"]

WATCHLIST_PREDEFINED_SYMBOLS_NIFTYINFRA = ["NSE:NIFTYINFRA-INDEX", "NSE:ADANIPORTS-EQ","NSE:ADANIPOWER-EQ","NSE:BHEL-EQ","NSE:BHARTIARTL-EQ","NSE:INFRATEL-EQ","NSE:CGPOWER-EQ","NSE:CONCOR-EQ","NSE:ENGINERSIN-EQ","NSE:GMRINFRA-EQ","NSE:IRB-EQ","NSE:IDEA-EQ","NSE:INDIGO-EQ","NSE:LT-EQ","NSE:NBCC-EQ","NSE:NCC-EQ","NSE:NHPC-EQ","NSE:NTPC-EQ","NSE:POWERGRID-EQ","NSE:RELINFRA-EQ","NSE:RPOWER-EQ","NSE:SIEMENS-EQ","NSE:SUZLON-EQ","NSE:TATACOMM-EQ","NSE:TATAPOWER-EQ","NSE:VOLTAS-EQ"]

WATCHLIST_PREDEFINED_SYMBOLS_NIFTYMIDCAP50 = ["NSE:NIFTYMIDCAP50-INDEX", "NSE:ADANIENT-EQ","NSE:ADANIPOWER-EQ","NSE:AJANTPHARM-EQ","NSE:AMARAJABAT-EQ","NSE:APOLLOHOSP-EQ","NSE:APOLLOTYRE-EQ","NSE:ARVIND-EQ","NSE:BALKRISIND-EQ","NSE:BANKINDIA-EQ","NSE:BERGEPAINT-EQ","NSE:BHARATFORG-EQ","NSE:BIOCON-EQ","NSE:CANBK-EQ","NSE:CASTROLIND-EQ","NSE:CENTURYTEX-EQ","NSE:CHOLAFIN-EQ","NSE:DALMIABHA-EQ","NSE:DISHTV-EQ","NSE:DIVISLAB-EQ","NSE:ENGINERSIN-EQ","NSE:EXIDEIND-EQ","NSE:FEDERALBNK-EQ","NSE:GMRINFRA-EQ","NSE:GODREJIND-EQ","NSE:IDBI-EQ","NSE:IDFCFIRSTB-EQ","NSE:IDFC-EQ","NSE:IRB-EQ","NSE:IGL-EQ","NSE:JINDALSTEL-EQ","NSE:L&TFH-EQ","NSE:M&MFIN-EQ","NSE:MRPL-EQ","NSE:MINDTREE-EQ","NSE:MUTHOOTFIN-EQ","NSE:NBCC-EQ","NSE:PCJEWELLER-EQ","NSE:PAGEIND-EQ","NSE:RBLBANK-EQ","NSE:RCOM-EQ","NSE:RELINFRA-EQ","NSE:RPOWER-EQ","NSE:SRF-EQ","NSE:TVSMOTOR-EQ","NSE:TATACHEM-EQ","NSE:TATACOMM-EQ","NSE:TATAGLOBAL-EQ","NSE:UNIONBANK-EQ","NSE:UBL-EQ","NSE:VOLTAS-EQ"]




# Entire Dictionary

WATCHLIST_PREDEFINED_LIST = [
    [WATCHLIST_PREDEFINED_NAME_NIFTY50,WATCHLIST_PREDEFINED_SYMBOLS_NIFTY50],
    [WATCHLIST_PREDEFINED_NAME_NIFTYBANK,WATCHLIST_PREDEFINED_SYMBOLS_NIFTYBANK],
    [WATCHLIST_PREDEFINED_NAME_NIFTYNEXT50,WATCHLIST_PREDEFINED_SYMBOLS_NIFTYNEXT50],
    [WATCHLIST_PREDEFINED_NAME_NIFTYPHARMA,WATCHLIST_PREDEFINED_SYMBOLS_NIFTYPHARMA],
    [WATCHLIST_PREDEFINED_NAME_NIFTYIT,WATCHLIST_PREDEFINED_SYMBOLS_NIFTYIT],
    [WATCHLIST_PREDEFINED_NAME_NIFTYPRIVATEBANK,WATCHLIST_PREDEFINED_SYMBOLS_NIFTYPRIVATEBANK],
    [WATCHLIST_PREDEFINED_NAME_NIFTYPSUBANK,WATCHLIST_PREDEFINED_SYMBOLS_NIFTYPSUBANK],
    [WATCHLIST_PREDEFINED_NAME_NIFTYFINANCIAL,WATCHLIST_PREDEFINED_SYMBOLS_NIFTYFINANCIAL],
    [WATCHLIST_PREDEFINED_NAME_NIFTYAUTO,WATCHLIST_PREDEFINED_SYMBOLS_NIFTYAUTO],
    [WATCHLIST_PREDEFINED_NAME_NIFTYFMCG,WATCHLIST_PREDEFINED_SYMBOLS_NIFTYFMCG],
    [WATCHLIST_PREDEFINED_NAME_NIFTYMEDIA,WATCHLIST_PREDEFINED_SYMBOLS_NIFTYMEDIA],
    [WATCHLIST_PREDEFINED_NAME_NIFTYREALTY,WATCHLIST_PREDEFINED_SYMBOLS_NIFTYREALTY],
    [WATCHLIST_PREDEFINED_NAME_NIFTYMETALS,WATCHLIST_PREDEFINED_SYMBOLS_NIFTYMETALS],
    [WATCHLIST_PREDEFINED_NAME_NIFTYINDICES,WATCHLIST_PREDEFINED_SYMBOLS_NIFTYINDICES],
    [WATCHLIST_PREDEFINED_NAME_NIFTYCOMMODITIES,WATCHLIST_PREDEFINED_SYMBOLS_NIFTYCOMMODITIES],
    [WATCHLIST_PREDEFINED_NAME_NIFTYINFRA,WATCHLIST_PREDEFINED_SYMBOLS_NIFTYINFRA],
    [WATCHLIST_PREDEFINED_NAME_NIFTYENERGY,WATCHLIST_PREDEFINED_SYMBOLS_NIFTYENERGY],
    [WATCHLIST_PREDEFINED_NAME_NIFTYMIDCAP50,WATCHLIST_PREDEFINED_SYMBOLS_NIFTYMIDCAP50],
]



#Watchlist file names saved in s3
WATCHLIST_PREDEFINED_S3_FILE_NAME_NIFTY50 = "ind_nifty50list.csv"
WATCHLIST_PREDEFINED_S3_FILE_NAME_NIFTYBANK = "ind_niftybanklist.csv"
WATCHLIST_PREDEFINED_S3_FILE_NAME_NIFTYNEXT50 = "ind_niftynext50list.csv"
WATCHLIST_PREDEFINED_S3_FILE_NAME_NIFTYPHARMA = "ind_niftypharmalist.csv"
WATCHLIST_PREDEFINED_S3_FILE_NAME_NIFTYIT = "ind_niftyitlist.csv"
WATCHLIST_PREDEFINED_S3_FILE_NAME_NIFTYPRIVATEBANK = "ind_nifty_privatebanklist.csv"
WATCHLIST_PREDEFINED_S3_FILE_NAME_NIFTYPSUBANK = "ind_niftypsubanklist.csv"
WATCHLIST_PREDEFINED_S3_FILE_NAME_NIFTYFINANCIAL = "ind_niftyfinancelist.csv"
WATCHLIST_PREDEFINED_S3_FILE_NAME_NIFTYAUTO = "ind_niftyautolist.csv"
WATCHLIST_PREDEFINED_S3_FILE_NAME_NIFTYFMCG = "ind_niftyfmcglist.csv"
WATCHLIST_PREDEFINED_S3_FILE_NAME_NIFTYMEDIA = "ind_niftymedialist.csv"
WATCHLIST_PREDEFINED_S3_FILE_NAME_NIFTYREALTY = "ind_niftyrealtylist.csv"
WATCHLIST_PREDEFINED_S3_FILE_NAME_NIFTYMETALS = "ind_niftymetallist.csv"
WATCHLIST_PREDEFINED_S3_FILE_NAME_NIFTYCOMMODITIES = "ind_niftycommoditieslist.csv"
WATCHLIST_PREDEFINED_S3_FILE_NAME_NIFTYINFRA = "ind_niftyinfralist.csv"
WATCHLIST_PREDEFINED_S3_FILE_NAME_NIFTYENERGY = "ind_niftyenergylist.csv"
WATCHLIST_PREDEFINED_S3_FILE_NAME_NIFTYMIDCAP50 = "ind_niftymidcap50list.csv"
#Newly added - Rushbh 1648030070
WATCHLIST_PREDEFINED_S3_FILE_NAME_NIFTYOILGAS = "ind_niftyoilgaslist.csv"
WATCHLIST_PREDEFINED_S3_FILE_NAME_NIFTYHEALTHCARE = "ind_niftyhealthcarelist.csv"

## Predefined Lists Cache Keys - 20191111 - Khyati
CACHE_K_WL_NIFTY50           = "Nifty50"
CACHE_K_WL_NIFTYBANK         = "NiftyBank"
CACHE_K_WL_NIFTYNEXT50       = "NiftyNext50"
CACHE_K_WL_NIFTYIT           = "NiftyIT"
CACHE_K_WL_NIFTYPHARMA       = "NiftyPharma"
CACHE_K_WL_NIFTYPRIVATEBANK  = "NiftyPrivateBank"
CACHE_K_WL_NIFTYPSUBANK      = "NiftyPSUBank"
CACHE_K_WL_NIFTYFINANCIAL    = "NiftyFinancials"
CACHE_K_WL_NIFTYAUTO         = "NiftyAuto"
CACHE_K_WL_NIFTYFMCG         = "NiftyFMCG"
CACHE_K_WL_NIFTYMEDIA        = "NiftyMedia"
CACHE_K_WL_NIFTYREALTY       = "NiftyRealty"
CACHE_K_WL_NIFTYMETALS       = "NiftyMetals"
CACHE_K_WL_NIFTYCOMMODITIES  = "NiftyCommodities"
CACHE_K_WL_NIFTYENERGY       = "NiftyEnergy"
CACHE_K_WL_NIFTYINFRA        = "NiftyInfra"
CACHE_K_WL_NIFTYMIDCAP50     = "NiftyMidcap50"
CACHE_K_WL_NIFTYINDICES      = "NiftyIndices"
#newly added - Rushbh 1648030070
CACHE_K_WL_NIFTYOILGAS       = "NiftyOilGas"
CACHE_K_WL_NIFTYHEALTHCARE   = "NiftyHealthcare"

WATCHLIST_NEW_PREDEFINED_LIST = [
    [WATCHLIST_PREDEFINED_NAME_NIFTY50,WATCHLIST_PREDEFINED_S3_FILE_NAME_NIFTY50,CACHE_K_WL_NIFTY50,"NSE:NIFTY50-INDEX"],
    [WATCHLIST_PREDEFINED_NAME_NIFTYBANK,WATCHLIST_PREDEFINED_S3_FILE_NAME_NIFTYBANK,CACHE_K_WL_NIFTYBANK,"NSE:NIFTYBANK-INDEX"],
    [WATCHLIST_PREDEFINED_NAME_NIFTYNEXT50,WATCHLIST_PREDEFINED_S3_FILE_NAME_NIFTYNEXT50,CACHE_K_WL_NIFTYNEXT50,"NSE:NIFTYNEXT50-INDEX"],
    [WATCHLIST_PREDEFINED_NAME_NIFTYPHARMA,WATCHLIST_PREDEFINED_S3_FILE_NAME_NIFTYPHARMA,CACHE_K_WL_NIFTYPHARMA, "NSE:NIFTYPHARMA-INDEX"],
    [WATCHLIST_PREDEFINED_NAME_NIFTYIT,WATCHLIST_PREDEFINED_S3_FILE_NAME_NIFTYIT,CACHE_K_WL_NIFTYIT, "NSE:NIFTYIT-INDEX"],
    [WATCHLIST_PREDEFINED_NAME_NIFTYPRIVATEBANK,WATCHLIST_PREDEFINED_S3_FILE_NAME_NIFTYPRIVATEBANK,CACHE_K_WL_NIFTYPRIVATEBANK,"NSE:NIFTYPVTBANK-INDEX"],
    [WATCHLIST_PREDEFINED_NAME_NIFTYPSUBANK,WATCHLIST_PREDEFINED_S3_FILE_NAME_NIFTYPSUBANK,CACHE_K_WL_NIFTYPSUBANK,"NSE:NIFTYPSUBANK-INDEX"],
    [WATCHLIST_PREDEFINED_NAME_NIFTYFINANCIAL,WATCHLIST_PREDEFINED_S3_FILE_NAME_NIFTYFINANCIAL,CACHE_K_WL_NIFTYFINANCIAL,"NSE:NIFTYFINSERVICE-INDEX"],
    [WATCHLIST_PREDEFINED_NAME_NIFTYAUTO,WATCHLIST_PREDEFINED_S3_FILE_NAME_NIFTYAUTO,CACHE_K_WL_NIFTYAUTO,"NSE:NIFTYAUTO-INDEX"],
    [WATCHLIST_PREDEFINED_NAME_NIFTYFMCG,WATCHLIST_PREDEFINED_S3_FILE_NAME_NIFTYFMCG,CACHE_K_WL_NIFTYFMCG,"NSE:NIFTYFMCG-INDEX"],
    [WATCHLIST_PREDEFINED_NAME_NIFTYMEDIA,WATCHLIST_PREDEFINED_S3_FILE_NAME_NIFTYMEDIA,CACHE_K_WL_NIFTYMEDIA,"NSE:NIFTYMEDIA-INDEX"],
    [WATCHLIST_PREDEFINED_NAME_NIFTYREALTY,WATCHLIST_PREDEFINED_S3_FILE_NAME_NIFTYREALTY,CACHE_K_WL_NIFTYREALTY,"NSE:NIFTYREALTY-INDEX"],
    [WATCHLIST_PREDEFINED_NAME_NIFTYMETALS,WATCHLIST_PREDEFINED_S3_FILE_NAME_NIFTYMETALS,CACHE_K_WL_NIFTYMETALS,"NSE:NIFTYMETAL-INDEX"],
    [WATCHLIST_PREDEFINED_NAME_NIFTYCOMMODITIES,WATCHLIST_PREDEFINED_S3_FILE_NAME_NIFTYCOMMODITIES,CACHE_K_WL_NIFTYCOMMODITIES,"NSE:NIFTYCOMMODITIES-INDEX"],
    [WATCHLIST_PREDEFINED_NAME_NIFTYINFRA,WATCHLIST_PREDEFINED_S3_FILE_NAME_NIFTYINFRA,CACHE_K_WL_NIFTYINFRA,"NSE:NIFTYINFRA-INDEX"],
    [WATCHLIST_PREDEFINED_NAME_NIFTYENERGY,WATCHLIST_PREDEFINED_S3_FILE_NAME_NIFTYENERGY,CACHE_K_WL_NIFTYENERGY,"NSE:NIFTYENERGY-INDEX"],
    [WATCHLIST_PREDEFINED_NAME_NIFTYMIDCAP50,WATCHLIST_PREDEFINED_S3_FILE_NAME_NIFTYMIDCAP50,CACHE_K_WL_NIFTYMIDCAP50,"NSE:NIFTYMIDCAP50-INDEX"],

    [WATCHLIST_PREDEFINED_NAME_NIFTYOILGAS,WATCHLIST_PREDEFINED_S3_FILE_NAME_NIFTYOILGAS,CACHE_K_WL_NIFTYOILGAS,"NSE:NIFTYOIL&GAS-INDEX"],
    [WATCHLIST_PREDEFINED_NAME_NIFTYHEALTHCARE,WATCHLIST_PREDEFINED_S3_FILE_NAME_NIFTYHEALTHCARE,CACHE_K_WL_NIFTYHEALTHCARE,"NSE:NIFTYHEALTHCARE-INDEX"],
]

